baseURL: http://cashweaver.com/
languageCode: en-us
title: Cash Weaver
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20

params:
  env: production
  description: "My personal website and blog."
  author: "Cash Weaver"

  googleAnalytics: UA-69408538-1

  ShowToc: true
  ShowReadingTime: true
  defaultTheme: auto
  ShowCodeCopyButtons: true
  hideSummaries: false

  homeInfoParams:
    Title: "Hi there 👋"
    Content: >-
      Welcome to my personal website and blog.

  socialIcons:
    - name: github
      url: "https://github.com/cashweaver"
    - name: twitter
      url: "https://twitter.com/cashweaver"
    - name: linkedin
      url: "https://linkedin.com/in/cashweaver"

  editPost:
    URL: "https://github.com/cashweaver/roam/tree/main"
    Text: "Suggest Changes"
    appendFilePath: true

  outputs:
    home:
        - HTML
        - RSS
        - JSON

  fuseOpts:
    isCaseSensitive: false
