baseURL: http://cashweaver.com/
languageCode: en-us
title: Cash Weaver
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Blog and notes"
  author: "Cash Weaver"

  googleAnalytics: UA-69408538-1

  ShowToc: true
  ShowReadingTime: true
  defaultTheme: auto
  ShowCodeCopyButtons: true
  hideSummaries: false

  homeInfoParams:
    Title: "Hi there 👋"
    Content: |-
      Welcome to my personal website and blog! I suggest starting one of the [posts I've written](/tags/cashweaver):

      1. [README](/posts/readme)
      1. [Polyphasic Sleep: 40 day trial results](/posts/polyphasic_sleep_40_day_trial_results)
      1. [How I Write My Blog](/posts/how_i_write_my_blog)

  socialIcons:
    - name: github
      url: "https://github.com/cashweaver"
    - name: twitter
      url: "https://twitter.com/cashweaver"
    - name: linkedin
      url: "https://linkedin.com/in/cashweaver"
    - name: instagram
      url: "https://instagram.com/cashweaver"
    - name: mealie
      url: "https://mealie.cashweaver.com"

  editPost:
    URL: "https://github.com/cashweaver/roam/tree/main"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
