baseURL = "http://cashweaver.com/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
theme = "PaperMod"
title = "Cash Weaver"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowToc = true
DateFormat = "2006-01-02"
author = "Cash Weaver"
defaultTheme = "auto"
description = "Blog and notes"
env = "production"
googleAnalytics = "UA-69408538-1"
hideSummary = false
hideMeta = false
showAuthor = false
enableMathjax = true

  [params.editPost]
  URL = "https://github.com/cashweaver/roam/tree/main"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = """
This website contains my personal notes.

The key component of my notes are the [links which connect them](/posts/6037800d-34c3-4d62-a33b-3931d694f083). Links allow forward movement (e.g. A to B). Backlinks allow backward movement (e.g. B to A). These sorts of interconnected notes are sometimes called [zettelkasten](/posts/b130e6f2-31a1-4c3a-ae8b-7d8208a69710), a second brain, a digital garden. They are a type of [personal knowledge management](/posts/773406e0-fe95-41f4-a254-b2c6ade18ce9) system.

I write these notes for myself and share them online as a way of increasing accountability for myself. The public nature of the notes encourages me to [think carefully about my own thoughts](/posts/efe31d96-34a6-439a-a34d-fdff9df0e51a) and [how I write](/posts/05911fff-a79b-4462-bf6d-a3cec4e1c9f2).

Check out the [archives](/archives) for a full list of posts or start from one of my favorites:

1. [The Meditations of the Emperor Marcus Antoninus](/posts/84e0e30f-a362-4aae-b540-4541e00af0a8)
1. [Tell all the truth but tell it slant](/posts/af1ca7da-bebf-4161-8162-057cae4a0951)
1. [Play to Win](/posts/4398317e-6aa1-4dd4-b2a5-6334256ca2cc)

I also post vegan cooking [recipes](/tags/recipe), [ingredients](/tags/ingredient), techniques, etc.
"""

  [[params.socialIcons]]
  name = "email"
  url = "mailto:cashbweaver@gmail.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/cashweaver"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/cashweaver"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/cashweaver"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/cashweaver"

  [[params.socialIcons]]
  name = "recipes"
  url = "/tags/recipe/"

[markup.goldmark.renderer]
unsafe = true
