baseURL: http://cashweaver.com/
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
theme: PaperMod
title: Cash Weaver

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowToc: true
  DateFormat: "2006-01-01"

  author: "Cash Weaver"
  defaultTheme: auto
  description: "Blog and notes"
  env: production
  googleAnalytics: UA-69408538-1
  hideSummaries: false
  showAuthor: false

  editPost:
    URL: "https://github.com/cashweaver/roam/tree/main"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false

  homeInfoParams:
    Title: "Hi there 👋"
    Content: |-
      This website contains my personal notes and thoughts. The key component of my notes are the [links which connect them](/posts/evergreennotesshouldbedenselylinked). Links allow forward movement (e.g. A to B). Backlinks allow backward movement (e.g. B to A). These sorts of interconnected notes are sometimes called [zettelkasten](/posts/zettelkasten2021), a second brain, a digital garden. They are a type of [personal knowledge management](/posts/personal_knowledge_management) system.

      I write these notes for myself and share them online as a way of increasing accountability for myself. The public nature of the notes encourages me to [prefer the explicit over the implicit](/posts/be_explicit), to think carefully about my own thoughts and [the way I write](/posts/style_guide).

  socialIcons:
    - name: email
      url: "mailto:cashbweaver@gmail.com"
    - name: github
      url: "https://github.com/cashweaver"
    - name: twitter
      url: "https://twitter.com/cashweaver"
    - name: linkedin
      url: "https://linkedin.com/in/cashweaver"
    - name: instagram
      url: "https://instagram.com/cashweaver"
    - name: mealie
      url: "https://mealie.cashweaver.com"

markup:
  goldmark:
    renderer:
      unsafe: true
