baseURL: http://cashweaver.com/
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
theme: PaperMod
title: Cash Weaver

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowToc: true
  DateFormat: "2006-01-01"

  author: "Cash Weaver"
  defaultTheme: auto
  description: "Blog and notes"
  env: production
  googleAnalytics: UA-69408538-1
  hideSummaries: false
  showAuthor: false

  editPost:
    URL: "https://github.com/cashweaver/roam/tree/main"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false

  homeInfoParams:
    Title: "Hi there 👋"
    Content: |-
      Welcome to my personal website and blog! I suggest starting one of the [posts I've written](/tags/cash-weaver):

      1. [README](/posts/readme)
      1. [Polyphasic Sleep: 40 day trial results](/posts/polyphasic_sleep_40_day_trial_results)
      1. [How I Write My Blog](/posts/how_i_write_my_blog)

  socialIcons:
    - name: github
      url: "https://github.com/cashweaver"
    - name: twitter
      url: "https://twitter.com/cashweaver"
    - name: linkedin
      url: "https://linkedin.com/in/cashweaver"
    - name: instagram
      url: "https://instagram.com/cashweaver"
    - name: mealie
      url: "https://mealie.cashweaver.com"

markup:
  goldmark:
    renderer:
      unsafe: true
