baseURL: http://cashweaver.com/
languageCode: en-us
title: Cash Weaver
theme: PaperMod
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
params:
  ShowToc: true
  defaultTheme: auto
  homeInfoParams:
    Title: "Cash Weaver"
    Content: >-
      My personal website and blog.
