baseURL = "http://notes.cashpw.com/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
theme = "PaperModX"
title = "Cash Prokop-Weaver"
googleAnalytics = "UA-69408538-1"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
DateFormat = "2006-01-02"
# Instant click breaks some javascript
EnableInstantClick = false
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowToc = true
TocOpen = true
TocSide = "left"
author = "Cash Prokop-Weaver"
defaultTheme = "dark"
description = "Blog and notes"
enableMathjax = true
env = "production"
hideMeta = false
hideSummary = false
showAuthor = false

  [params.editPost]
  URL = "https://github.com/cashpw/notes/edit/main"
  Text = "Edit"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = """
These are my [interlinked](/posts/6037800d-34c3-4d62-a33b-3931d694f083) [personal](/posts/2c8acd36-620a-47a7-8d3a-63594fd2065c) notes ([how](/posts/5140bc26-825e-4e26-aec6-3738a5fe2ab1), [why](/posts/7add4362-8a4e-4148-ac25-185213327b33)). These sorts of interconnected notes are a type of [personal knowledge management](/posts/773406e0-fe95-41f4-a254-b2c6ade18ce9) system. They're sometimes called [zettelkasten](/posts/b130e6f2-31a1-4c3a-ae8b-7d8208a69710), a second brain, or a digital garden.

Check out the [archives](/archives) for a full list of posts or start from one of my [favorites](/posts/2a586a0e-eddc-4903-9c90-7e3a91e3204c) or a (vegan) [recipe](/tags/recipe)/[ingredient](/tags/ingredient).
"""

  [[params.socialIcons]]
  name = "email"
  url = "mailto:cashbweaver@gmail.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/cashpw"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/cashweaver"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/cashweaver"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/cashweaver"

  [[params.socialIcons]]
  name = "recipes"
  url = "/tags/recipe/"

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.mounts]]
    source = "static"
    target = "assets"
